### PR TITLE
the big cleanup part 1

### PR DESCRIPTION
**Pull request by stefanpenner**
- [ ] good tests
- [ ] better usage
- [ ] ~~promise array~~ future work.

### CODE REVIEW

**Comment by jakecraige** [comment]
yesss. Maybe we'll actually be able to do some work on this now, lol

**Comment by stefanpenner** [comment]
bbl in a-few hours, gotta go shopping.

**Comment by stefanpenner** [comment]
> bbl in a-few hours, gotta go shopping.

my shopping experience turned into an all day event :P

**Comment by stefanpenner** [comment]
- [ ] @domenics `last`

**Comment by stefanpenner** [comment]
now stale

**Comment by jakecraige** [comment]
lol, definitely! 😂

**Pull request closed without merging**
